application: fridge-cop
version: 6
runtime: python27
api_version: 1
threadsafe: yes
default_expiration: "365d"
skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*\.psd$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/bin/.*$
- ^(.*/)?.*/sensor_broadcast/.*$
- ^(.*/)?.*/stress_test/.*$
- ^(.*/)?.*/build/.*$

handlers:

- url: /css
  expiration: "365d"
  static_dir: css

- url: /images
  expiration: "365d"
  static_dir: images

- url: /js
  expiration: "365d"
  static_dir: js
  
- url: /fonts
  expiration: "365d"
  static_dir: fonts  
 
- url: /favicon\.ico
  expiration: "7d"
  static_files: favicon.ico
  upload: favicon\.ico

- url: /admin/test
  script: main.bottle
  login: admin
  
- url: /.*
  script: main.bottle

